# Generated by Django 4.2.7 on 2024-01-08 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='cpf',
            field=models.CharField(default=None, unique=True),
        ),
    ]
