# Generated by Django 4.2.7 on 2023-11-17 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('cor', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sobre', models.TextField(blank=True, null=True)),
                ('situacao_atual', models.TextField(blank=True, null=True)),
                ('prioridade', models.CharField(max_length=5)),
                ('prazo', models.DateField()),
                ('link', models.CharField(max_length=100)),
                ('proximos_passos', models.TextField(blank=True, null=True)),
                ('impedimentos', models.TextField(blank=True, null=True)),
                ('sistema_critico', models.BooleanField(default=False)),
                ('pasta_responsavel', models.CharField(max_length=8)),
                ('data_criacao', models.DateTimeField(auto_now=True)),
                ('setor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projetos.setor')),
                ('status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projetos.status')),
            ],
        ),
    ]
