# Generated by Django 4.2.7 on 2024-01-17 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pessoas', '0003_alter_pessoa_cpf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contas',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('senha', models.CharField(max_length=50, null=True)),
                ('cpf', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pessoas.pessoa', to_field='cpf')),
            ],
        ),
    ]
