# Generated by Django 4.2.7 on 2024-01-17 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0003_alter_pessoa_cpf'),
        ('contas_acesso', '0003_contas_id_alter_contas_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contas',
            name='cpf',
            field=models.ForeignKey(max_length=11, on_delete=django.db.models.deletion.CASCADE, to='pessoas.pessoa', to_field='cpf', verbose_name='cpf'),
        ),
    ]
